use_frameworks!

target 'PopupBridge_Example' do
  pod 'PopupBridge', :path => '../'

  target 'PopupBridge_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
