language: objective-c
osx_image: xcode12.3

branches:
  only:
  - master

cache:
  bundler: true
  cocoapods: true

script:
  - set -o pipefail && xcodebuild -workspace PopupBridge.xcworkspace -scheme Demo -destination platform\=iOS\ Simulator,OS\=14.3,name\=iPhone\ 12 test | bundle exec xcpretty -c
